baseurl = "https://hss-mateus.github.io/blog"
defaultContentLanguage = "pt-br"
theme = "hello-friend"
paginate = 5
disqusShortname = "hssmateus"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 0

  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.pt-br]
    title = "hss-mateus"
    subtitle = "Meu blog pessoal"
    keywords = ""
    copyright = ""
    menuMore = "Mostrar mais"
    writtenBy = "Escrito por"
    readMore = "Ler mais"
    readOtherPosts = "Leia mais posts"
    newerPosts = "Posts mais novos"
    olderPosts = "Posts mais antigos"
    minuteReadingTime = "min lidos"
    dateFormatSingle = "02/01/2006"
    dateFormatList = "02/01/2006"

    [languages.pt-br.params.logo]
      logoText = "hss-mateus"
      logoHomeLink = "/blog"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    # [languages.pt-br.menu]
      # [[languages.pt.menu.main]]
      #   identifier = "sobre"
      #   name = "Sobre"
      #   url = "/sobre"
      # [[languages.pt.menu.main]]
      #   identifier = "projetos"
      #   name = "Projetos"
      #   url = "/projetos"